name = "thegd33"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "GD33V2"
database_id = "b38148fa-7325-4c06-99a3-ebeed3c8ea6f"

# Cloudflare R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "boutiqueop"
