name = "thegd33"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "gd33v3-db"
database_id = "86c41062-615a-43e3-ba18-f7fd4b0ca9aa"

# Cloudflare R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "boutiqueop"
